main_app/urls.py
from django.urls import path, include
from django.views.generic.edit import CreateView
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('pets/heaven/', views.heaven, name="heaven"),
    path('about/', views.about, name="about"),
    path('pets/', views.pets_index, name="index"),
    path('pets/<int:pet_id>/', views.pets_detail, name="detail"),
    path('pets/create/', views.PetCreate.as_view(), name='pets_create'),
    path('pets/<int:pk>/update/', views.PetUpdate.as_view(), name='pets_update'),
    path('pets/<int:pet_id>/heaven/', views.send_heaven, name='send_heaven'),
    path('pets/<int:pk>/delete/', views.PetDelete.as_view(), name='pets_delete'),
    path('pets/<int:pet_id>/add_energy/', views.add_energy, name='add_energy'),
    path('pets/<int:pet_id>/heaven_true/', views.heaven_true, name='heaven_true'),
    path('pets/<int:pet_id>/add_home/', views.add_home, name='add_home'),
    path('pets/<int:pet_id>/add_photo/', views.add_photo, name="add_photo"),
    path('pets/search/', views.pets_search, name='pets_search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
]

petspetsadopter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, date
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

ENERGY_SOURCES = (
    ('F', 'Food'),
    ('W', 'Water'),
    ('S', 'Snack'),
    ('L', 'Sunlight'),
)

SIZES = (
    ('T', 'Extra Small'),
    ('S', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
    ('X', 'Extra Large'),
    ('H', 'Huge'),
)

STYLES = (
    ('B', 'Blanket'),
    ('P', 'Pillow'),
    ('A', 'Apartment'),
    ('C', 'Condo'),
    ('H', 'House'),
    ('T', 'Aquarium'),
    ('L', 'Clay Pot'),
    ('V', 'Vase'),
    ('E', 'Petri Dish'),
)


class Pet(models.Model):
    name = models.CharField(max_length=100)
    kingdom = models.CharField(max_length=100)
    species = models.CharField(max_length=150)
    common_name = models.CharField(max_length=100)
    birthday = models.DateField(null=True)
    height = models.FloatField('Height (in)')
    weight = models.FloatField('Weight (lbs)')
    intro = models.TextField(max_length=300)
    heaven = models.BooleanField(default=False)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pet_id': self.id})

    def add_energy(request, pet_id):
        form = EnergyForm(request.POST)
        if form.is_valid():
            new_energy

    def energized_infull(self):
        return self.energy_set.filter(date=date.today()).count() >= 3

    def add_home(request, pet_id):
        form = HomeForm(request.POST)
        if form.is_valid():
            new_home

    def today_energy(self):
        current_date = date.today()
        return self.energy_set.filter(date=current_date)

class Energy(models.Model):
    date = models.DateTimeField()
    energy_source = models.CharField(
        max_length=1,
        choices=ENERGY_SOURCES,
        default=ENERGY_SOURCES[0][0]
    )
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_energy_source_display()} on {self.date}"

    @property
    def is_today(self):
        print(self.date.strftime("%Y-%m-%d"))
        print(date.today())
        print(self.date.strftime("%Y-%m-%d") == date.today().strftime("%Y-%m-%d"))
        return self.date.strftime("%Y-%m-%d") == date.today().strftime("%Y-%m-%d")
        # return self.date == date.today()

    class Meta:
        ordering = ['-date']


class Home(models.Model):
    color = models.CharField(
        max_length=30,
        default='White',
    )
    style = models.CharField(
        max_length=1,
        choices=STYLES,
        default=STYLES[0][0]
    )
    size = models.CharField(
        max_length=1,
        choices=SIZES,
        default=SIZES[0][0]
    )
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

    def __str__(self):
        return f"A {self.get_size_display()}, {self.color} {self.get_style_display()}"

    class Meta:
        ordering = ['style']

class Photo(models.Model):
    url = models.CharField(max_length=250)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for pet_id: {self.pet_id}, {self.pet.name} @ {self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Energy, Pet, Home, User

class EnergyForm(ModelForm):
    class Meta:
        model = Energy
        fields = ['energy_source', 'date']

class UserSignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'email']

class HeavenForm(ModelForm):
    class Meta:
        model = Pet
        fields = ['heaven']

class HomeForm(ModelForm):
    class Meta:
        model = Home
        fields = ['style', 'size', 'color']

main_app/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.http import HttpResponse, HttpRequest
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
import uuid
import boto3
from .forms import EnergyForm, HeavenForm, HomeForm
from .filters import PetFilter
from django.db.models import Q
from .models import Pet, Home, Photo

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'petspetsadopter'

# Create your views here.
def home(request):
    pets = Pet.objects.all()
    return render(request, 'home.html', {'pets': pets})

def heaven(request):
    pets = Pet.objects.all()
    return render(request, 'pets/heaven.html', {'pets': pets})

def about(request):
    return render(request, 'about.html')

def pets_index(request):

    query_string=request.GET.get('q')
    if query_string == None:
        pets = Pet.objects.all()
        return render(request, 'pets/index.html', {'pets': pets})
    else:    
        pets = Pet.objects.filter(Q(name__icontains=query_string) | Q(kingdom__icontains=query_string) | Q(common_name__icontains=query_string) | Q(species__icontains=query_string))
        return render(request, 'pets/index.html', {'pets': pets})

def pets_detail(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    energy_form = EnergyForm()
    home_form = HomeForm()
    return render(request, 'pets/detail.html', { 
        'pet': pet, 'energy_form': energy_form,
        'home_form': home_form,
    })

def add_energy(request, pet_id):
    energy_form = EnergyForm(request.POST)
    if energy_form.is_valid():
        new_energy = energy_form.save(commit=False)
        new_energy.pet_id = pet_id
        new_energy.save()
    return redirect('detail', pet_id=pet_id)


class PetCreate(CreateView):
    model = Pet
    fields = ['name', 'kingdom', 'species', 'common_name', 'birthday', 'height', 'weight', 'intro']
    success_url = '/pets/'

class PetUpdate(UpdateView):
    model = Pet
    fields = ['kingdom', 'species', 'common_name', 'birthday', 'height', 'weight']

class PetDelete(DeleteView):
    model = Pet
    success_url = '/pets/'


def heaven_true(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    heaven_form = HeavenForm(request.POST)
    if heaven_form.is_valid():
        pet.heaven = True
        pet.save()
    return redirect('/pets/heaven/')

def send_heaven(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    heaven_form = HeavenForm()
    return render(request, 'pets/send_heaven.html', { 
        'pet': pet, 'heaven_form': heaven_form 
    })

def add_home(request, pet_id):
    home_form = HomeForm(request.POST)
    if home_form.is_valid():
        new_home = home_form.save(commit=False)
        new_home.pet_id = pet_id
        new_home.save()
    return redirect('detail', pet_id=pet_id)

# def delete_home(request, pet_id):


def items_index(request):
    pets = Pet.objects.heaven_set == False
    homes = Home.objects.all()
    return render(request, 'items/index.html', {'pets': pets, 'homes': homes})

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid credentials - try again'
            
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)
    
def pets_search(request):
    pet_list = Pet.objects.all()
    pet_filter = PetFilter(request.GET, queryset=pet_list)
    return render(request, 'pet_list.html', {'filter': pet_filter})

def add_photo(request, pet_id):
	# photo-file was the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # assign to pet_id or pet(if I have a pet object
            photo = Photo(url=url, pet_id=pet_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', pet_id=pet_id)

main_app/templates/pets/detail.html
{% extends 'base.html' %}
{% block content %}

<h3 class="center-align">{{pet.name}}'s Bio</h3>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-image">
        {% for photo in pet.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel green-text center-align">No Photos Uploaded</div>
        {% endfor %}

      </div>
    </div>
    <div class="card">
      <div class="card-content card-content-link">
        <span class="pet-name">Hi, I'm {{pet.name}}!</span>
        <p>Kingdom: {{pet.kingdom}}</p>
        <p>Species: {{pet.species}}</p>
        <p>Species, common: {{pet.common_name}}</p>
        {% if pet.age > 0 %}
        <p>Age: {{pet.age}}</p>
        {% else %}
        <p>Age: Just made it out into the world!</p>
        {% endif %}
        <p>Height: {{pet.height}}</p>
        <p>Weight: {{pet.weight}}</p>
        <div class="card-action">
          <a href="{% url 'pets_update' pet.id %}">Edit Bio</a>
          <a>|</a>
          <a href="{% url 'send_heaven' pet.id %}">Send to Heaven</a>
        </div>
      </div>
    </div>

    {% if pet.photo_set.count %}
    {%else%}
    <div class="card">
      <form action="{% url 'add_photo' pet.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn green" value="Upload Photo">
      </form>
    </div>
    {% endif %}



  </div>


  <div class="col s6">
    <table class="striped centered">
      <thead>
        <tr>
          <th>Energy</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        {% for energy in pet.energy_set.all %}
        {% if energy.is_today %}
        <tr>
          <td>{{energy.get_energy_source_display}}</td>
          <td>{{energy.date}}</td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
    <form action="{% url 'add_energy' pet.id %}" method="post">
      {% csrf_token %}
      {{energy_form.as_table}}
      <input type="submit" class="btn green" value="Energize {{pet.name}}">
    </form>
    <br>
    {% if pet.energized_infull %}
    <div class="card-panel green-text center-align">{{pet.name}} has received enough energy for today</div>
    {% else %}
    <div class="card-panel red-text center-align">{{pet.name}} might be feeling sluggish</div>
    {% endif %}
  </div>

  <div class="row">
    <div class="col s6">
      {% if pet.home_set.count %}
      {% for home in pet.home_set.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <h5>Living Quarters</h5>
            <h6>{{home.get_size_display}} {{home.color}} {{home.get_style_display}}</h6>
          </span>
          {% endfor %}
          {% else %}
          <h4>Housing</h4>
          <p>Help {{pet.name}} find a home</p>
          <form action="{% url 'add_home' pet.id %}" method="post">
            {% csrf_token %}
            {{ home_form.as_table }}
            <input type="submit" value="Get Home" class="btn green">
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var selectEl = document.getElementById('id_style');
  M.FormSelect.init(selectEl);
  var selectEl = document.getElementById('id_size');
  M.FormSelect.init(selectEl);
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_energy_source');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/pets/heaven.html
{% extends 'base.html' %}
{% block content %}

<h3 class="center-align">Pets Pets in Heaven</h3>
<p>Currently, these pets are all in a better place.</p>
{% for pet in pets %}
{% if pet.heaven == True %}
<div class='card'>
    <a href="{% url 'detail' pet.id %}">
        <div class='card-content black-text'>
            <span class='card-title'>{{ pet.name }}, {{pet.common_name}}</span>
            <p>Kingdom: {{pet.kingdom}}</p>
            {% if pet.age > 0 %}
            <p>Age: {{pet.age}}</p>
            {% else %}
            <p>Age: Just made it out into the world!</p>
            {% endif %}
        </div>
    </a>
</div>
{% endif %}
{% endfor %}

{% endblock %}

main_app/templates/pets/index.html
{% extends 'base.html' %}
{% block content %}

<div class="block">
    <div class="header">
        <h3 class="center-align">Meet the Pets Pets</h3>
    </div>
    <div class="search center-align" style="height: 40px">
        <form action="" method="GET">
            <input
                style="border-bottom: 2px solid green; border-top: 2px; width: 50%; min-width: 350px; text-align: center; height:40px; margin: 0; align-self: center"
                type="text" name="q" autocomplete="off">
            <button class="btn green" style="align-self: center" type="submit">Find A Pet</button>
            <!-- <button class="btn green" style="align-self: center" >All Pets</button> -->
        </form>
    </div>
</div>
<br>


<div class="row pets-index">
    {% for pet in pets %}
    {% if pet.heaven == false %}
    <div class="col s6" style="justify-content: stretch;">
        <div class="card" style="margin-top: 50px">
            <div class="card-image">
                {% for photo in pet.photo_set.all %}
                <img src="{{photo.url}}">
                {% endfor %}
            </div>
            <a href="{% url 'detail' pet.id %}">
                <div class="card-content black-text">
                    <p>{{pet.name}}, {{pet.common_name}}</p>
                    <p>{{pet.intro}}</p>
                </div>
            </a>
        </div>
    </div>
    {% endif%}
    {% empty %}

    <p>No Pet like the one you are looking for. Look for another pet!</p>

    {% endfor %}
</div>

{% endblock %}

main_app/templates/pets/send_heaven.html
{% extends 'base.html' %}
{% block content %}

<h3 class="center-align">Time to let {{pet.name}} go to Heaven?</h3>
<h4>Are you sure you want to send <span class="green-text">{{pet.name}}</span> to <span class="green-text">heaven</span>?</h4>


<form action="{% url 'heaven_true' pet.id %}" method="post">
    {% csrf_token %}
    {{heaven_form.as_p}}
    <a href="{% url 'detail' pet.id %}" class="btn-large green">{{object.name}} needs more time on Earth</a>
        <input type="submit" class="btn-large green" value="Send {{pet.name}} to Heaven">
      </form>

{% endblock %}